# Generated by Django 5.0.1 on 2024-01-20 10:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название списка')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена продукта')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимальное количество товара не может быть меньше 1')], verbose_name='Количество единиц товара')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления товара в')),
                ('purchase_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaselist', verbose_name='Список покупок')),
            ],
            options={
                'ordering': ['price'],
                'indexes': [models.Index(fields=['name'], name='purchase_pr_name_33abb1_idx')],
            },
        ),
    ]
