# Generated by Django 5.0.1 on 2024-01-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='purchaselist',
            options={'verbose_name': 'Список', 'verbose_name_plural': 'Списки'},
        ),
    ]
