# Generated by Django 5.0.1 on 2024-01-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_product_options_alter_purchaselist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание списка с набором продуктов'),
        ),
    ]
