# Generated by Django 5.0.1 on 2024-01-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaselist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_list',
        ),
        migrations.DeleteModel(
            name='PurchaseList',
        ),
    ]
